import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  zh: {
    // Common
    'common.loading': '加载中...',
    'common.submit': '提交',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.save': '保存',
    'common.back': '返回',
    'common.confirm': '确认',
    'common.search': '搜索',
    
    // Auth
    'auth.login': '登录',
    'auth.logout': '退出登录',
    'auth.username': '用户名',
    'auth.enterUsername': '请输入用户名',
    'auth.quickLogin': '或快速登录',
    'auth.enterSystem': '进入系统',
    'auth.firstLoginGift': '首次登录将自动建账户,初始积分1000',
    'auth.localStorageNote': '本系统使用本地存储,数据仅保存在浏览器中',
    'auth.pleaseLogin': '请先登录',
    'auth.returnLogin': '返回登录',
    
    // Navigation
    'nav.dashboard': '控制台',
    'nav.matches': '比赛记录',
    'nav.topics': '投票与下注',
    'nav.profile': '个人中心',
    'nav.settings': '设置',
    'nav.discordBot': 'Discord Bot设置',
    
    // Dashboard
    'dashboard.welcome': '欢迎回来',
    'dashboard.coach': '教练',
    'dashboard.readyForNextMatch': '准备好分析您的下一场比赛了吗?',
    'dashboard.totalMatches': '总比赛数',
    'dashboard.uploadFirstMatch': '开始上传您的第一场比赛',
    'dashboard.avgTTD': '平均TTD',
    'dashboard.ttdAnalysis': '决策时间分析',
    'dashboard.teamCollab': '团队协同',
    'dashboard.comboWinRate': '组合胜率统计',
    'dashboard.activeTopics': '活跃话题',
    'dashboard.votingBetting': '投票与下注',
    'dashboard.quickStart': '快速开始',
    'dashboard.chooseFeature': '选择一个功能开始使用',
    'dashboard.viewMatches': '查看比赛记录',
    'dashboard.joinVoting': '参与投票话题',
    'dashboard.personalCenter': '个人中心',
    'dashboard.uploadDemo': '上传比赛Demo',
    'dashboard.features': '功能亮点',
    'dashboard.learnCapabilities': '了解平台核心能力',
    'dashboard.smartPhaseDetection': '智能阶段识别',
    'dashboard.autoDetectTurningPoints': '自动检测比赛中的关键转折点',
    'dashboard.collabAnalysis': '协同效率分析',
    'dashboard.findBestCombos': '发现最佳配合组合',
    'dashboard.aiSuggestions': 'AI驱动建议',
    'dashboard.getActionableAdvice': '获得可执行的改进方案',
    
    // Matches
    'matches.title': '比赛记录',
    'matches.description': '查看和分析您的历史比赛',
    'matches.uploadDemo': '上传Demo',
    'matches.noMatches': '还没有比赛记录',
    'matches.uploadToStart': '上传CS demo文件开始分析您的比赛表现',
    'matches.uploadFirst': '上传第一场比赛',
    'matches.uploader': '上传者',
    'matches.viewAnalysis': '查看分析',
    'matches.winner': '获胜',
    'matches.draw': '平局',
    'matches.deleteConfirm': '确定要删除这场比赛吗?',
    'matches.deleted': '比赛已删除',
    
    // Match Upload
    'upload.title': '上传比赛Demo',
    'upload.description': '上传CS官方demo文件进行赛后分析',
    'upload.selectFile': '选择Demo文件',
    'upload.supportedFormats': '支持CS:GO和CS2的.dem格式文件',
    'upload.clickOrDrag': '点击或拖拽文件到此处',
    'upload.maxSize': '支持.dem格式,最大100MB',
    'upload.reselect': '重新选择',
    'upload.matchInfo': '比赛信息',
    'upload.fillBasicInfo': '填写比赛的基本信息',
    'upload.mapName': '地图名称',
    'upload.mapPlaceholder': '例如: de_dust2, de_mirage',
    'upload.teamAName': '队伍A名称',
    'upload.teamBName': '队伍B名称',
    'upload.teamAScore': '队伍A得分',
    'upload.teamBScore': '队伍B得分',
    'upload.uploading': '上传中...',
    'upload.uploadAndAnalyze': '上传并分析',
    'upload.fileSelected': '文件已选择',
    'upload.selectDemFile': '请选择.dem格式的CS demo文件',
    'upload.pleaseSelectFile': '请选择demo文件',
    'upload.fillComplete': '请填写完整的比赛信息',
    'upload.success': '上传成功!',
    'upload.matchSaved': '比赛已保存',
    'upload.failed': '上传失败',
    'upload.checkFormat': '请检查文件格式',
    
    // Topics
    'topics.title': '投票与下注',
    'topics.description': '参与社区话题讨论和预测',
    'topics.myPoints': '我的积分',
    'topics.createTopic': '创建话题',
    'topics.noTopics': '暂无活跃话题',
    'topics.createFirst': '创建第一个话题开始互动',
    'topics.vote': '投票',
    'topics.bet': '下注',
    'topics.active': '进行中',
    'topics.closed': '已截止',
    'topics.revealed': '已揭晓',
    'topics.participants': '参与人数',
    'topics.totalPool': '奖池总额',
    'topics.viewDetail': '查看详情',
    'topics.deleteConfirm': '确定要删除这个话题吗?',
    'topics.deleted': '话题已删除',
    
    // Topic Detail
    'topic.backToList': '返回话题列表',
    'topic.status': '状态',
    'topic.revealTime': '揭晓时间',
    'topic.yourChoice': '您的选择',
    'topic.notParticipated': '未参与',
    'topic.pointsSpent': '已投入',
    'topic.points': '积分',
    'topic.statistics': '统计信息',
    'topic.totalVotes': '总投票数',
    'topic.options': '选项',
    'topic.chooseOption': '选择一个选项',
    'topic.betAmount': '下注积分',
    'topic.minBet': '最少10积分',
    'topic.insufficientPoints': '积分不足',
    'topic.submitVote': '提交投票',
    'topic.submitBet': '提交下注',
    'topic.alreadyParticipated': '您已参与过此话题',
    'topic.topicClosed': '话题已截止',
    'topic.selectOption': '请选择一个选项',
    'topic.enterBetAmount': '请输入下注积分',
    'topic.minBetRequired': '最少下注10积分',
    'topic.notEnoughPoints': '积分不足',
    'topic.voteSuccess': '投票成功!',
    'topic.betSuccess': '下注成功!',
    'topic.pointsDeducted': '积分已扣除',
    
    // Create Topic
    'createTopic.title': '创建话题',
    'createTopic.description': '创建新的投票或下注话题',
    'createTopic.basicInfo': '基本信息',
    'createTopic.topicTitle': '话题标题',
    'createTopic.titlePlaceholder': '输入吸引人的话题标题',
    'createTopic.topicDescription': '话题描述',
    'createTopic.descriptionPlaceholder': '详细描述话题内容和规则',
    'createTopic.topicType': '话题类型',
    'createTopic.typeVote': '投票 - 匿名参与,无积分消耗',
    'createTopic.typeBet': '下注 - 需要投入积分,猜对可获得奖励',
    'createTopic.optionsSetup': '选项设置',
    'createTopic.addOption': '添加选项',
    'createTopic.optionPlaceholder': '选项',
    'createTopic.minTwoOptions': '至少需要2个选项',
    'createTopic.revealTime': '揭晓时间',
    'createTopic.selectDateTime': '选择话题截止和揭晓的时间',
    'createTopic.create': '创建话题',
    'createTopic.fillRequired': '请填写所有必填项',
    'createTopic.success': '话题创建成功!',
    'createTopic.adminOnly': '只有管理员可以创建话题',
    'createTopic.noPermission': '权限不足',
    
    // Profile
    'profile.title': '个人中心',
    'profile.info': '个人信息',
    'profile.pointsHistory': '积分明细',
    'profile.username': '用户名',
    'profile.role': '角色',
    'profile.roleAdmin': '管理员',
    'profile.roleUser': '普通用户',
    'profile.joinDate': '注册时间',
    'profile.currentPoints': '当前积分',
    'profile.pointsSummary': '积分统计',
    'profile.totalEarned': '总获得',
    'profile.totalSpent': '总消耗',
    'profile.balance': '当前余额',
    'profile.noTransactions': '暂无积分变动记录',
    'profile.transactionType': '交易类型',
    'profile.system': '系统赠送',
    'profile.bet': '下注消耗',
    'profile.win': '中奖获得',
    'profile.refund': '退款',
    'profile.relatedTopic': '相关话题',
    
    // Discord
    'discord.title': 'Discord Bot 设置',
    'discord.description': '配置和管理您的Discord机器人',
    'discord.tokenSetup': 'Bot Token 配置',
    'discord.enterToken': '输入您的Discord Bot Token',
    'discord.tokenPlaceholder': '粘贴您的Bot Token',
    'discord.howToGet': '如何获取Token?',
    'discord.step1': '1. 访问 Discord Developer Portal',
    'discord.step2': '2. 创建新应用或选择现有应用',
    'discord.step3': '3. 在Bot页面复制Token',
    'discord.step4': '4. 将Bot邀请到您的服务器',
    'discord.saveToken': '保存Token',
    'discord.botStatus': 'Bot 状态',
    'discord.online': '在线',
    'discord.offline': '离线',
    'discord.startBot': '启动Bot',
    'discord.stopBot': '停止Bot',
    'discord.features': '功能特性',
    'discord.aiChat': 'AI教练问答 (!ask)',
    'discord.voiceJoin': '语音频道连接 (!join/!leave)',
    'discord.dataQuery': '数据查询 (!stats, !matches)',
    'discord.adminOnly': '管理员专用',
    'discord.tokenSaved': 'Token已保存',
    'discord.botStarted': 'Bot已启动',
    'discord.botStopped': 'Bot已停止',
    'discord.enterTokenFirst': '请先输入Bot Token',
    
    // App Title
    'app.title': 'FPS 团队赛后教练 AI Agent',
    'app.subtitle': '数据驱动的FPS团队赛后分析平台',
  },
  en: {
    // Common
    'common.loading': 'Loading...',
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.save': 'Save',
    'common.back': 'Back',
    'common.confirm': 'Confirm',
    'common.search': 'Search',
    
    // Auth
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.username': 'Username',
    'auth.enterUsername': 'Enter username',
    'auth.quickLogin': 'Or Quick Login',
    'auth.enterSystem': 'Enter System',
    'auth.firstLoginGift': 'First login will auto-create account with 1000 points',
    'auth.localStorageNote': 'This system uses local storage, data is saved in browser only',
    'auth.pleaseLogin': 'Please login first',
    'auth.returnLogin': 'Return to Login',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.matches': 'Matches',
    'nav.topics': 'Voting & Betting',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.discordBot': 'Discord Bot Settings',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.coach': 'Coach',
    'dashboard.readyForNextMatch': 'Ready to analyze your next match?',
    'dashboard.totalMatches': 'Total Matches',
    'dashboard.uploadFirstMatch': 'Start uploading your first match',
    'dashboard.avgTTD': 'Avg TTD',
    'dashboard.ttdAnalysis': 'Decision Time Analysis',
    'dashboard.teamCollab': 'Team Collaboration',
    'dashboard.comboWinRate': 'Combo Win Rate Stats',
    'dashboard.activeTopics': 'Active Topics',
    'dashboard.votingBetting': 'Voting & Betting',
    'dashboard.quickStart': 'Quick Start',
    'dashboard.chooseFeature': 'Choose a feature to get started',
    'dashboard.viewMatches': 'View Match History',
    'dashboard.joinVoting': 'Join Voting Topics',
    'dashboard.personalCenter': 'Personal Center',
    'dashboard.uploadDemo': 'Upload Match Demo',
    'dashboard.features': 'Features',
    'dashboard.learnCapabilities': 'Learn about core capabilities',
    'dashboard.smartPhaseDetection': 'Smart Phase Detection',
    'dashboard.autoDetectTurningPoints': 'Auto-detect key turning points in matches',
    'dashboard.collabAnalysis': 'Collaboration Analysis',
    'dashboard.findBestCombos': 'Discover best team combinations',
    'dashboard.aiSuggestions': 'AI-Driven Suggestions',
    'dashboard.getActionableAdvice': 'Get actionable improvement plans',
    
    // Matches
    'matches.title': 'Match History',
    'matches.description': 'View and analyze your historical matches',
    'matches.uploadDemo': 'Upload Demo',
    'matches.noMatches': 'No match records yet',
    'matches.uploadToStart': 'Upload CS demo files to start analyzing your performance',
    'matches.uploadFirst': 'Upload First Match',
    'matches.uploader': 'Uploader',
    'matches.viewAnalysis': 'View Analysis',
    'matches.winner': 'Winner',
    'matches.draw': 'Draw',
    'matches.deleteConfirm': 'Are you sure you want to delete this match?',
    'matches.deleted': 'Match deleted',
    
    // Match Upload
    'upload.title': 'Upload Match Demo',
    'upload.description': 'Upload CS official demo file for post-match analysis',
    'upload.selectFile': 'Select Demo File',
    'upload.supportedFormats': 'Supports CS:GO and CS2 .dem format files',
    'upload.clickOrDrag': 'Click or drag file here',
    'upload.maxSize': 'Supports .dem format, max 100MB',
    'upload.reselect': 'Reselect',
    'upload.matchInfo': 'Match Information',
    'upload.fillBasicInfo': 'Fill in basic match information',
    'upload.mapName': 'Map Name',
    'upload.mapPlaceholder': 'e.g.: de_dust2, de_mirage',
    'upload.teamAName': 'Team A Name',
    'upload.teamBName': 'Team B Name',
    'upload.teamAScore': 'Team A Score',
    'upload.teamBScore': 'Team B Score',
    'upload.uploading': 'Uploading...',
    'upload.uploadAndAnalyze': 'Upload & Analyze',
    'upload.fileSelected': 'File selected',
    'upload.selectDemFile': 'Please select a .dem format CS demo file',
    'upload.pleaseSelectFile': 'Please select demo file',
    'upload.fillComplete': 'Please fill in complete match information',
    'upload.success': 'Upload successful!',
    'upload.matchSaved': 'Match saved',
    'upload.failed': 'Upload failed',
    'upload.checkFormat': 'Please check file format',
    
    // Topics
    'topics.title': 'Voting & Betting',
    'topics.description': 'Participate in community discussions and predictions',
    'topics.myPoints': 'My Points',
    'topics.createTopic': 'Create Topic',
    'topics.noTopics': 'No active topics',
    'topics.createFirst': 'Create first topic to start interaction',
    'topics.vote': 'Vote',
    'topics.bet': 'Bet',
    'topics.active': 'Active',
    'topics.closed': 'Closed',
    'topics.revealed': 'Revealed',
    'topics.participants': 'Participants',
    'topics.totalPool': 'Total Pool',
    'topics.viewDetail': 'View Details',
    'topics.deleteConfirm': 'Are you sure you want to delete this topic?',
    'topics.deleted': 'Topic deleted',
    
    // Topic Detail
    'topic.backToList': 'Back to Topics',
    'topic.status': 'Status',
    'topic.revealTime': 'Reveal Time',
    'topic.yourChoice': 'Your Choice',
    'topic.notParticipated': 'Not Participated',
    'topic.pointsSpent': 'Points Spent',
    'topic.points': 'Points',
    'topic.statistics': 'Statistics',
    'topic.totalVotes': 'Total Votes',
    'topic.options': 'Options',
    'topic.chooseOption': 'Choose an option',
    'topic.betAmount': 'Bet Amount',
    'topic.minBet': 'Minimum 10 points',
    'topic.insufficientPoints': 'Insufficient points',
    'topic.submitVote': 'Submit Vote',
    'topic.submitBet': 'Submit Bet',
    'topic.alreadyParticipated': 'You have already participated',
    'topic.topicClosed': 'Topic closed',
    'topic.selectOption': 'Please select an option',
    'topic.enterBetAmount': 'Please enter bet amount',
    'topic.minBetRequired': 'Minimum bet is 10 points',
    'topic.notEnoughPoints': 'Not enough points',
    'topic.voteSuccess': 'Vote successful!',
    'topic.betSuccess': 'Bet successful!',
    'topic.pointsDeducted': 'Points deducted',
    
    // Create Topic
    'createTopic.title': 'Create Topic',
    'createTopic.description': 'Create new voting or betting topic',
    'createTopic.basicInfo': 'Basic Information',
    'createTopic.topicTitle': 'Topic Title',
    'createTopic.titlePlaceholder': 'Enter an attractive topic title',
    'createTopic.topicDescription': 'Topic Description',
    'createTopic.descriptionPlaceholder': 'Describe topic content and rules in detail',
    'createTopic.topicType': 'Topic Type',
    'createTopic.typeVote': 'Vote - Anonymous participation, no points cost',
    'createTopic.typeBet': 'Bet - Requires points, win rewards for correct guess',
    'createTopic.optionsSetup': 'Options Setup',
    'createTopic.addOption': 'Add Option',
    'createTopic.optionPlaceholder': 'Option',
    'createTopic.minTwoOptions': 'At least 2 options required',
    'createTopic.revealTime': 'Reveal Time',
    'createTopic.selectDateTime': 'Select topic deadline and reveal time',
    'createTopic.create': 'Create Topic',
    'createTopic.fillRequired': 'Please fill in all required fields',
    'createTopic.success': 'Topic created successfully!',
    'createTopic.adminOnly': 'Only admins can create topics',
    'createTopic.noPermission': 'Insufficient permissions',
    
    // Profile
    'profile.title': 'Profile',
    'profile.info': 'Personal Information',
    'profile.pointsHistory': 'Points History',
    'profile.username': 'Username',
    'profile.role': 'Role',
    'profile.roleAdmin': 'Admin',
    'profile.roleUser': 'User',
    'profile.joinDate': 'Join Date',
    'profile.currentPoints': 'Current Points',
    'profile.pointsSummary': 'Points Summary',
    'profile.totalEarned': 'Total Earned',
    'profile.totalSpent': 'Total Spent',
    'profile.balance': 'Balance',
    'profile.noTransactions': 'No transaction records',
    'profile.transactionType': 'Type',
    'profile.system': 'System Gift',
    'profile.bet': 'Bet Cost',
    'profile.win': 'Win Reward',
    'profile.refund': 'Refund',
    'profile.relatedTopic': 'Related Topic',
    
    // Discord
    'discord.title': 'Discord Bot Settings',
    'discord.description': 'Configure and manage your Discord bot',
    'discord.tokenSetup': 'Bot Token Setup',
    'discord.enterToken': 'Enter your Discord Bot Token',
    'discord.tokenPlaceholder': 'Paste your Bot Token',
    'discord.howToGet': 'How to get Token?',
    'discord.step1': '1. Visit Discord Developer Portal',
    'discord.step2': '2. Create new app or select existing',
    'discord.step3': '3. Copy Token from Bot page',
    'discord.step4': '4. Invite Bot to your server',
    'discord.saveToken': 'Save Token',
    'discord.botStatus': 'Bot Status',
    'discord.online': 'Online',
    'discord.offline': 'Offline',
    'discord.startBot': 'Start Bot',
    'discord.stopBot': 'Stop Bot',
    'discord.features': 'Features',
    'discord.aiChat': 'AI Coach Q&A (!ask)',
    'discord.voiceJoin': 'Voice Channel (!join/!leave)',
    'discord.dataQuery': 'Data Query (!stats, !matches)',
    'discord.adminOnly': 'Admin Only',
    'discord.tokenSaved': 'Token saved',
    'discord.botStarted': 'Bot started',
    'discord.botStopped': 'Bot stopped',
    'discord.enterTokenFirst': 'Please enter Bot Token first',
    
    // App Title
    'app.title': 'FPS Team Post-Match Coach AI Agent',
    'app.subtitle': 'Data-Driven FPS Team Post-Match Analysis Platform',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'en' || saved === 'zh') ? saved : 'zh';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['zh']] || key;
  };

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
