import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  zh: {
    // Common
    'common.loading': '加载中...',
    'common.submit': '提交',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.save': '保存',
    'common.back': '返回',
    'common.confirm': '确认',
    'common.search': '搜索',
    
    // Auth
    'auth.login': '登录',
    'auth.logout': '退出登录',
    'auth.username': '用户名',
    'auth.enterUsername': '请输入用户名',
    'auth.quickLogin': '或快速登录',
    'auth.enterSystem': '进入系统',
    'auth.firstLoginGift': '首次登录将自动建账户,初始积分1000',
    'auth.localStorageNote': '本系统使用本地存储,数据仅保存在浏览器中',
    'auth.pleaseLogin': '请先登录',
    'auth.returnLogin': '返回登录',
    'auth.quickLoginAdmin': '管理员',
    'auth.quickLoginPlayerA': '玩家A',
    'auth.quickLoginPlayerB': '玩家B',
    
    // Navigation
    'nav.dashboard': '控制台',
    'nav.matches': '比赛记录',
    'nav.topics': '投票与下注',
    'nav.profile': '个人中心',
    'nav.settings': '设置',
    'nav.discordBot': 'Discord Bot设置',
    
    // Dashboard
    'dashboard.welcome': '欢迎回来',
    'dashboard.coach': '教练',
    'dashboard.readyForNextMatch': '准备好分析您的下一场比赛了吗?',
    'dashboard.totalMatches': '总比赛数',
    'dashboard.uploadFirstMatch': "let's continue !",
    'dashboard.avgTTD': '平均TTD',
    'dashboard.ttdAnalysis': '决策时间分析',
    'dashboard.teamCollab': '团队协同',
    'dashboard.comboWinRate': '组合胜率统计',
    'dashboard.activeTopics': '活跃话题',
    'dashboard.votingBetting': '投票与下注',
    'dashboard.quickStart': '快速开始',
    'dashboard.chooseFeature': '选择一个功能开始使用',
    'dashboard.viewMatches': '查看比赛记录',
    'dashboard.joinVoting': '参与投票话题',
    'dashboard.personalCenter': '个人中心',
    'dashboard.uploadDemo': '上传比赛Demo',
    'dashboard.features': 'Recent Voting',
    
    'dashboard.smartPhaseDetection': '智能阶段识别',
    'dashboard.autoDetectTurningPoints': '自动检测比赛中的关键转折点',
    'dashboard.collabAnalysis': '协同效率分析',
    'dashboard.findBestCombos': '发现最佳配合组合',
    'dashboard.aiSuggestions': 'AI驱动建议',
    'dashboard.getActionableAdvice': '获得可执行的改进方案',
    
    // Matches
    'matches.title': '比赛记录',
    'matches.description': '查看和分析您的历史比赛',
    'matches.uploadDemo': '上传Demo',
    'matches.noMatches': '还没有比赛记录',
    'matches.uploadToStart': '上传CS demo文件开始分析您的比赛表现',
    'matches.uploadFirst': '上传第一场比赛',
    'matches.uploader': '上传者',
    'matches.viewAnalysis': '查看分析',
    'matches.winner': '获胜',
    'matches.draw': '平局',
    'matches.duration': '用时',
    'matches.viewDetail': '查看详情',
    'matches.pendingScore': '等待比分',
    'matches.unknownDuration': '未记录',
    'matches.invalidMatch': '无法找到指定的比赛',
    'matches.deleteConfirm': '确定要删除这场比赛吗?',
    'matches.deleted': '比赛已删除',

    // Analysis
    'analysis.phaseBreakdown': '阶段时长分布',
    'analysis.phaseBreakdownDesc': '热手/正常/低迷/恢复阶段占比',
    'analysis.eventBreakdown': '事件分布',
    'analysis.eventBreakdownDesc': '击杀、放包、技能等关键事件频次',
    'analysis.ttdDistribution': 'TTD分布',
    'analysis.ttdDistributionDesc': '决策时间直方图 (ms)',
    'analysis.voiceQuality': '语音质量雷达',
    'analysis.voiceQualityDesc': '清晰度、信息密度与打断率',
    'analysis.comboPerformance': '组合胜率',
    'analysis.comboPerformanceDesc': '团队配合组合的胜率表现',
    'analysis.noData': '暂无数据',
    'analysis.loading': '加载中...',
    'analysis.live': '实时分析',

    // Match Detail
    'matchDetail.title': '比赛详情 #{id}',
    'matchDetail.liveData': '实时数据',
    'matchDetail.overview': '比赛概览',
    'matchDetail.overviewDesc': '地图、时间、比分与文件信息',
    'matchDetail.teams': '对战队伍',
    'matchDetail.score': '比分',
    'matchDetail.duration': '时长',
    'matchDetail.schedule': '开始时间',
    'matchDetail.endTime': '结束时间',
    'matchDetail.summary': '关键摘要',
    'matchDetail.summaryDesc': 'TTD、语音质量、组合胜率快照',
    'matchDetail.ttdLabel': 'TTD P50 / P90',
    'matchDetail.voiceQuality': '语音清晰度',
    'matchDetail.comboLabel': '最佳组合',
    'matchDetail.phases': '阶段分布',
    'matchDetail.phasesDesc': '热手/正常/低迷/恢复阶段及转折点',
    'matchDetail.noPhases': '暂无阶段数据',
    'matchDetail.phaseDuration': '阶段时长',
    'matchDetail.changePoint': '转折评分',
    'matchDetail.events': '关键事件',
    'matchDetail.eventsDesc': '按时间排序的击杀、放包等事件',
    'matchDetail.noEvents': '暂无事件记录',
    'matchDetail.ttd': '决策时间 (TTD)',
    'matchDetail.ttdDesc': 'P50/P90、均值与样本细节',
    'matchDetail.noTtd': '暂无TTD样本',
    'matchDetail.mean': '均值',
    'matchDetail.samples': '样本数',
    'matchDetail.noData': '暂无数据',
    'matchDetail.voice': '语音回合',
    'matchDetail.voiceDesc': '清晰度、信息密度与中断率',
    'matchDetail.noVoice': '暂无语音记录',
    'matchDetail.clarity': '清晰度',
    'matchDetail.infoDensity': '信息密度',
    'matchDetail.interruptions': '打断率',
    'matchDetail.turns': '回合数',
    'matchDetail.noTranscript': '未提供文本',
    'matchDetail.sentiment': '情绪',
    'matchDetail.combos': '团队配合',
    'matchDetail.combosDesc': '组合尝试次数、成功数与胜率',
    'matchDetail.noCombos': '暂无配合数据',
    'matchDetail.comboContext': '配合场景',
    'matchDetail.attempts': '尝试次数',
    'matchDetail.success': '成功/尝试',
    'matchDetail.winRate': '胜率',
    
    // Match Upload
    'upload.title': '上传比赛Demo',
    'upload.description': '上传CS官方demo文件进行赛后分析',
    'upload.selectFile': '选择Demo文件',
    'upload.supportedFormats': '支持CS:GO和CS2的.dem格式文件',
    'upload.clickOrDrag': '点击或拖拽文件到此处',
    'upload.maxSize': '支持.dem格式,最大100MB',
    'upload.reselect': '重新选择',
    'upload.matchInfo': '比赛信息',
    'upload.fillBasicInfo': '填写比赛的基本信息',
    'upload.mapName': '地图名称',
    'upload.mapPlaceholder': '例如: de_dust2, de_mirage',
    'upload.teamAName': '队伍A名称',
    'upload.teamAPlaceholder': '队伍A',
    'upload.teamBName': '队伍B名称',
    'upload.teamBPlaceholder': '队伍B',
    'upload.teamAScore': '队伍A得分',
    'upload.teamBScore': '队伍B得分',
    'upload.uploading': '上传中...',
    'upload.uploadAndAnalyze': '上传并分析',
    'upload.fileSelected': '文件已选择',
    'upload.selectDemFile': '请选择.dem格式的CS demo文件',
    'upload.pleaseSelectFile': '请选择demo文件',
    'upload.fillComplete': '请填写完整的比赛信息',
    'upload.success': '上传成功!',
    'upload.matchSaved': '比赛已保存',
    'upload.failed': '上传失败',
    'upload.checkFormat': '请检查文件格式',
    
    // Topics
    'topics.title': '投票与下注',
    'topics.description': '参与社区话题讨论和预测',
    'topics.myPoints': '我的积分',
    'topics.createTopic': '创建话题',
    'topics.noTopics': '暂无活跃话题',
    'topics.createFirst': '创建第一个话题开始互动',
    'topics.vote': '投票',
    'topics.bet': '下注',
    'topics.mission': '隐秘任务',
    'topics.active': '进行中',
    'topics.closed': '已截止',
    'topics.revealed': '已揭晓',
    'topics.participants': '参与人数',
    'topics.totalPool': '奖池总额',
    'topics.viewDetail': '查看详情',
    'topics.deleteConfirm': '确定要删除这个话题吗?',
    'topics.deleted': '话题已删除',
    'topics.waitForAdmin': '等待管理员创建话题',
    'topics.missionReward': '完成奖励 +{points} 积分',
    'topics.missionOutcome': '由创建者结算',

    // Topic Detail
    'topic.backToList': '返回话题列表',
    'topic.status': '状态',
    'topic.revealTime': '揭晓时间',
    'topic.yourChoice': '您的选择',
    'topic.notParticipated': '未参与',
    'topic.pointsSpent': '已投入',
    'topic.points': '积分',
    'topic.statistics': '统计信息',
    'topic.totalVotes': '总投票数',
    'topic.options': '选项',
    'topic.chooseOption': '选择一个选项',
    'topic.betAmount': '下注积分',
    'topic.minBet': '最少10积分',
    'topic.insufficientPoints': '积分不足',
    'topic.submitVote': '提交投票',
    'topic.submitBet': '提交下注',
    'topic.alreadyParticipated': '您已参与过此话题',
    'topic.topicClosed': '话题已截止',
    'topic.selectOption': '请选择一个选项',
    'topic.enterBetAmount': '请输入下注积分',
    'topic.minBetRequired': '最少下注10积分',
    'topic.notEnoughPoints': '积分不足',
    'topic.voteSuccess': '投票成功!',
    'topic.betSuccess': '下注成功!',
    'topic.pointsDeducted': '积分已扣除',
    'chat.revealLoginRequired': '请先登录后再结算结果',
    'chat.noActiveTopics': '暂无需要结算的话题',
    'chat.revealMessage': '已为「{title}」揭晓结果：{choice}。竞猜积分已结算。',
    'chat.revealSuccess': '已揭晓并结算积分',
    'chat.revealFailed': '揭晓失败',
    'chat.autoCreateTopic': '自动创建话题',
    'chat.autoCreateSuccess': '话题已自动创建',
    'chat.autoCreateFailed': '自动创建话题失败',
    
    // Reveal Dialog
    'reveal.letsSeWhoWins': '揭晓时刻！',
    'reveal.tapToReveal': '点击卡片揭晓结果',
    'reveal.winner': '获胜选项',
    'reveal.yourPick': '你的选择',
    'reveal.participated': '已参与',
    'reveal.notParticipated': '未参与此话题',
    'reveal.pointsAtStake': '投注积分',
    'reveal.youWin': '恭喜获胜！',
    'reveal.youLose': '很遗憾...',
    'reveal.tapToContinue': '点击任意处继续',
    'common.close': '关闭',
    
    // Create Topic
    'createTopic.title': '创建话题',
    'createTopic.description': '创建新的投票或下注话题',
    'createTopic.basicInfo': '基本信息',
    'createTopic.topicTitle': '话题标题',
    'createTopic.titlePlaceholder': '输入吸引人的话题标题',
    'createTopic.topicDescription': '话题描述',
    'createTopic.descriptionPlaceholder': '详细描述话题内容和规则',
    'createTopic.topicType': '话题类型',
    'createTopic.typeVote': '投票 - 匿名参与,无积分消耗',
    'createTopic.typeBet': '下注 - 需要投入积分,猜对可获得奖励',
    'createTopic.optionsSetup': '选项设置',
    'createTopic.addOption': '添加选项',
    'createTopic.optionPlaceholder': '选项',
    'createTopic.minTwoOptions': '至少需要2个选项',
    'createTopic.revealTime': '揭晓时间',
    'createTopic.selectDateTime': '选择话题截止和揭晓的时间',
    'createTopic.create': '创建话题',
    'createTopic.fillRequired': '请填写所有必填项',
    'createTopic.success': '话题创建成功!',
    'createTopic.adminOnly': '只有管理员可以创建话题',
    'createTopic.noPermission': '权限不足',
    
    // Profile
    'profile.title': '个人中心',
    'profile.info': '个人信息',
    'profile.pointsHistory': '积分明细',
    'profile.username': '用户名',
    'profile.role': '角色',
    'profile.roleAdmin': '管理员',
    'profile.roleUser': '普通用户',
    'profile.joinDate': '注册时间',
    'profile.currentPoints': '当前积分',
    'profile.pointsSummary': '积分统计',
    'profile.totalEarned': '总获得',
    'profile.totalSpent': '总消耗',
    'profile.balance': '当前余额',
    'profile.noTransactions': '暂无积分变动记录',
    'profile.transactionType': '交易类型',
    'profile.system': '系统赠送',
    'profile.bet': '下注消耗',
    'profile.win': '中奖获得',
    'profile.refund': '退款',
    'profile.relatedTopic': '相关话题',
    
    // Discord
    'discord.title': 'Discord Bot 设置',
    'discord.description': '配置和管理您的Discord机器人',
    'discord.tokenSetup': 'Bot Token 配置',
    'discord.enterToken': '输入您的Discord Bot Token',
    'discord.tokenPlaceholder': '粘贴您的Bot Token',
    'discord.howToGet': '如何获取Token?',
    'discord.howToCreate': '如何创建Discord Bot',
    'discord.step1': '访问 Discord Developer Portal',
    'discord.step2': '创建新应用或选择现有应用',
    'discord.step3': '在Bot设置中启用"Message Content Intent"',
    'discord.step4': '复制Bot Token并粘贴到上方输入框',
    'discord.step5': '使用OAuth2 URL邀请Bot到你的服务器',
    'discord.saveToken': '保存Token',
    'discord.botStatus': 'Bot 状态',
    'discord.statusDescription': '查看Discord Bot当前运行状态',
    'discord.runningStatus': '运行状态',
    'discord.botUsername': 'Bot用户名',
    'discord.serverCount': '服务器数量',
    'discord.servers': '个服务器',
    'discord.tokenHelp': '从Discord Developer Portal获取Bot Token',
    'discord.botConfig': 'Bot配置',
    'discord.configDescription': '配置Discord Bot Token和权限',
    'discord.online': '在线',
    'discord.offline': '离线',
    'discord.startBot': '启动Bot',
    'discord.stopBot': '停止Bot',
    'discord.features': '功能特性',
    'discord.aiChat': 'AI教练问答 (!ask)',
    'discord.voiceJoin': '语音频道连接 (!join/!leave)',
    'discord.dataQuery': '数据查询 (!stats, !matches)',
    'discord.adminOnly': '管理员专用',
    'discord.tokenSaved': 'Token已保存',
    'discord.botStarted': 'Bot已启动',
    'discord.botStopped': 'Bot已停止',
    'discord.enterTokenFirst': '请先输入Bot Token',
    'discord.requiredPermissions': '所需权限',
    'discord.permissionRead': '读取消息',
    'discord.permissionSend': '发送消息',
    'discord.permissionConnect': '连接语音频道',
    'discord.permissionSpeak': '在语音频道中说话',
    'discord.availableCommands': '可用命令',
    'discord.commandsDescription': '在Discord中使用以下命令与Bot互动',
    'discord.dataSectionTitle': '📊 数据查询',
    'discord.voiceSectionTitle': '🎯 语音功能',
    'discord.interactSectionTitle': '🎲 互动功能',
    'discord.aiSectionTitle': '🤖 AI助手',
    'discord.statsCommand': '查看比赛统计',
    'discord.matchesCommand': '查看比赛列表',
    'discord.joinCommand': '加入语音频道',
    'discord.leaveCommand': '离开语音频道',
    'discord.topicsCommand': '查看投票话题',
    'discord.voteCommand': '参与投票',
    'discord.askCommand': '向AI教练提问',
    'discord.helpCommand': '查看帮助',
    'discord.startFailed': '启动失败',
    'discord.stopFailed': '停止失败',
    
    // App Title
    'app.title': 'FPS 团队赛后教练 AI Agent',
    'app.subtitle': '数据驱动的FPS团队赛后分析平台',
    'app.tagline': '让复盘从"感觉驱动"变为"数据驱动 + 有趣互动"',
    'app.enterSystem': '进入系统',
    'app.startJourney': '点击按钮开始您的数据分析之旅',

    // Pages
    'pages.analysis': '分析页面',
    'pages.settings': '设置页面',
    'pages.matchDetail': '比赛详情页面',
    'pages.componentShowcase': '组件展示',
    'pages.notFound': '页面未找到',

    // Component Showcase
    'showcase.title': 'Shadcn/ui 组件库',
    'showcase.textColors': '文本颜色',
    'showcase.foreground': '前景（默认）',
    'showcase.defaultText': '主要内容默认文本颜色',
    'showcase.mutedForeground': '弱化前景',
    'showcase.mutedText': '次要信息的弱化文本',
    'showcase.primary': '主要',
    'showcase.primaryText': '主要品牌颜色文本',
    'showcase.secondaryForeground': '次要前景',
    'showcase.secondaryText': '次要操作文本颜色',
    'showcase.accentForeground': '强调前景',
    'showcase.accentText': '用于强调的强调文本',
    'showcase.destructive': '破坏性',
    'showcase.destructiveText': '错误或破坏性操作文本',
    'showcase.cardForeground': '卡片前景',
    'showcase.cardText': '卡片背景上的文本颜色',
    'showcase.popoverForeground': '弹出前景',
    'showcase.popoverText': '弹出层中的文本颜色',
    'showcase.colorCombinations': '颜色组合',
    'showcase.primaryBg': '主要背景与前景文本',
    'showcase.secondaryBg': '次要背景与前景文本',
    'showcase.mutedBg': '弱化背景与前景文本',
    'showcase.accentBg': '强调背景与强调文本',
    'showcase.destructiveBg': '破坏性背景与前景文本',
    'showcase.cardBg': '卡片背景与前景文本',
    'showcase.popoverBg': '弹出背景与前景文本',
    'showcase.backgroundBg': '默认背景与前景文本',

    // Not Found
    'notFound.title': '页面未找到',
    'notFound.description': '您访问的页面不存在',
    'notFound.backHome': '返回首页',

    // Teams
    'teams.title': '团队',
    'teams.description': '管理你的团队和队员',
    'teams.myTeams': '我的团队',
    'teams.discoverTeams': '发现团队',
    'teams.createTeam': '创建团队',
    'teams.joinTeam': '加入团队',
    'teams.noTeams': '还没有加入团队',
    'teams.noTeamsDesc': '创建一个新团队或使用邀请码加入现有团队',
    'teams.noPublicTeams': '暂无公开团队',
    'teams.noPublicTeamsDesc': '目前没有可加入的公开团队',
    'teams.maxMembers': '最多 {count} 人',
    'teams.public': '公开',
    'teams.noDescription': '暂无团队描述',
    'teams.roleOwner': '队长',
    'teams.roleAdmin': '管理员',
    'teams.roleMember': '队员',
    'teams.createSuccess': '团队创建成功！',
    'teams.joinSuccess': '成功加入团队 {name}！',
    'teams.createNew': '创建新团队',
    'teams.createDesc': '创建一个团队来组织你的队友一起游戏',
    'teams.teamName': '团队名称',
    'teams.teamNamePlaceholder': '例如: Phoenix Rising',
    'teams.teamTag': '团队标签',
    'teams.teamTagPlaceholder': '例如: PHX',
    'teams.teamTagHint': '2-6个字符的简短标识',
    'teams.teamDescription': '团队描述',
    'teams.teamDescPlaceholder': '介绍一下你的团队...',
    'teams.maxMembersLabel': '最大成员数',
    'teams.publicTeam': '公开团队',
    'teams.publicTeamHint': '允许其他玩家发现并申请加入',
    'teams.creating': '创建中...',
    'teams.joinByCode': '加入团队',
    'teams.joinByCodeDesc': '输入邀请码加入一个现有团队',
    'teams.inviteCode': '邀请码',
    'teams.inviteCodePlaceholder': '例如: A1B2C3D4',
    'teams.inviteCodeHint': '向团队成员索取邀请码',
    'teams.joining': '加入中...',
    
    // Team Detail
    'teamDetail.notFound': '团队不存在',
    'teamDetail.notFoundDesc': '该团队可能已被解散或您没有访问权限',
    'teamDetail.backToList': '返回团队列表',
    'teamDetail.members': '成员',
    'teamDetail.youAre': '你是{role}',
    'teamDetail.editTeam': '编辑团队',
    'teamDetail.leaveTeam': '离开团队',
    'teamDetail.disbandTeam': '解散团队',
    'teamDetail.confirmLeave': '确认离开团队？',
    'teamDetail.leaveHint': '离开后需要重新获取邀请码才能加入。',
    'teamDetail.confirmDisband': '确认解散团队？',
    'teamDetail.disbandHint': '此操作不可撤销。所有成员将被移除，团队数据将被永久删除。',
    'teamDetail.confirmLeaveBtn': '确认离开',
    'teamDetail.confirmDisbandBtn': '确认解散',
    'teamDetail.leftTeam': '已离开团队',
    'teamDetail.disbanded': '团队已解散',
    'teamDetail.inviteCodeLabel': '邀请码 · 分享给朋友加入团队',
    'teamDetail.codeRefreshed': '邀请码已更新',
    'teamDetail.emptySlot': '空位',
    
    // Team Member
    'teamMember.edit': '编辑',
    'teamMember.kick': '移除成员',
    'teamMember.transfer': '转让队长',
    'teamMember.editMember': '编辑成员',
    'teamMember.editMemberDesc': '修改 {name} 的信息',
    'teamMember.nickname': '昵称',
    'teamMember.nicknamePlaceholder': '团队内昵称',
    'teamMember.position': '位置',
    'teamMember.positionPlaceholder': '选择位置',
    'teamMember.role': '角色',
    'teamMember.updated': '成员信息已更新',
    'teamMember.confirmKick': '移除成员？',
    'teamMember.kickHint': '确定要将 {name} 移出团队吗？',
    'teamMember.confirmKickBtn': '确认移除',
    'teamMember.kicked': '成员已移除',
    'teamMember.confirmTransfer': '转让队长？',
    'teamMember.transferHint': '确定要将队长转让给 {name} 吗？你将成为管理员。',
    'teamMember.confirmTransferBtn': '确认转让',
    'teamMember.transferred': '队长已转让',
    'teamMember.saving': '保存中...',
    
    // Team Edit
    'teamEdit.title': '编辑团队',
    'teamEdit.description': '修改团队信息和设置',
    'teamEdit.updated': '团队信息已更新',
    
    // Team Status
    'teamStatus.online': '在线',
    'teamStatus.offline': '离线',
    'teamStatus.inGame': '游戏中',
    'teamStatus.away': '离开',
    'teamStatus.onlineCount': '{online}/{total} 在线',
    'teamStatus.refresh': '刷新',
    'teamStatus.teamSettings': '团队设置',
    'teamStatus.inviteCode': '邀请码',
    'teamStatus.members': '队员',
    'teamStatus.memberCount': '{count}/{max}',
    'teamStatus.emptySlots': '空位',
    'teamStatus.waitingToJoin': '等待加入...',
    'teamStatus.viewDetails': '查看团队详情',
    'teamStatus.noTeam': '还没有加入团队',
    'teamStatus.noTeamDesc': '创建一个新团队或使用邀请码加入现有团队',
    'teamStatus.team': '团队',
    'teamStatus.joinOrCreate': '加入或创建一个团队开始协作',
    'teamStatus.loadFailed': '无法加载团队信息',
    
    // Positions
    'position.IGL': '指挥 (IGL)',
    'position.Entry': '突破手 (Entry)',
    'position.AWPer': '狙击手 (AWPer)',
    'position.Support': '辅助 (Support)',
    'position.Lurker': '潜伏者 (Lurker)',
    'position.Rifler': '步枪手 (Rifler)',
    'position.Flex': '全能 (Flex)',
    
    // Team Themes
    'teamTheme.title': '主题色',
    'teamTheme.selectTheme': '选择主题',
    'teamTheme.deepBlue': '深蓝幻紫',
    'teamTheme.deepBlueDesc': '经典电竞主题',
    'teamTheme.crimson': '绯红烈焰',
    'teamTheme.crimsonDesc': '战斗与激情',
    'teamTheme.gold': '荣耀之金',
    'teamTheme.goldDesc': '精英与管理',
    'teamTheme.purple': '电光霓紫',
    'teamTheme.purpleDesc': '社区与潮流',
  },
  en: {
    // Common
    'common.loading': 'Loading...',
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.save': 'Save',
    'common.back': 'Back',
    'common.confirm': 'Confirm',
    'common.search': 'Search',
    
    // Auth
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.username': 'Username',
    'auth.enterUsername': 'Enter username',
    'auth.quickLogin': 'Or Quick Login',
    'auth.enterSystem': 'Enter System',
    'auth.firstLoginGift': 'First login will auto-create account with 1000 points',
    'auth.localStorageNote': 'This system uses local storage, data is saved in browser only',
    'auth.pleaseLogin': 'Please login first',
    'auth.returnLogin': 'Return to Login',
    'auth.quickLoginAdmin': 'Admin',
    'auth.quickLoginPlayerA': 'Player A',
    'auth.quickLoginPlayerB': 'Player B',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.matches': 'Matches',
    'nav.topics': 'Voting & Betting',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.discordBot': 'Discord Bot Settings',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.coach': 'Coach',
    'dashboard.readyForNextMatch': 'Ready to analyze your next match?',
    'dashboard.totalMatches': 'Total Matches',
    'dashboard.uploadFirstMatch': "let's continue !",
    'dashboard.avgTTD': 'Avg TTD',
    'dashboard.ttdAnalysis': 'Decision Time Analysis',
    'dashboard.teamCollab': 'Team Collaboration',
    'dashboard.comboWinRate': 'Combo Win Rate Stats',
    'dashboard.activeTopics': 'Active Topics',
    'dashboard.votingBetting': 'Voting & Betting',
    'dashboard.quickStart': 'Quick Start',
    'dashboard.chooseFeature': 'Choose a feature to get started',
    'dashboard.viewMatches': 'View Match History',
    'dashboard.joinVoting': 'Join Voting Topics',
    'dashboard.personalCenter': 'Personal Center',
    'dashboard.uploadDemo': 'Upload Match Demo',
    'dashboard.features': 'Recent Voting',
    
    'dashboard.smartPhaseDetection': 'Smart Phase Detection',
    'dashboard.autoDetectTurningPoints': 'Auto-detect key turning points in matches',
    'dashboard.collabAnalysis': 'Collaboration Analysis',
    'dashboard.findBestCombos': 'Discover best team combinations',
    'dashboard.aiSuggestions': 'AI-Driven Suggestions',
    'dashboard.getActionableAdvice': 'Get actionable improvement plans',
    
    // Matches
    'matches.title': 'Match History',
    'matches.description': 'View and analyze your historical matches',
    'matches.uploadDemo': 'Upload Demo',
    'matches.noMatches': 'No match records yet',
    'matches.uploadToStart': 'Upload CS demo files to start analyzing your performance',
    'matches.uploadFirst': 'Upload First Match',
    'matches.uploader': 'Uploader',
    'matches.viewAnalysis': 'View Analysis',
    'matches.winner': 'Winner',
    'matches.draw': 'Draw',
    'matches.duration': 'Duration',
    'matches.viewDetail': 'View Detail',
    'matches.pendingScore': 'Pending score',
    'matches.unknownDuration': 'Unknown',
    'matches.invalidMatch': 'Cannot find this match',
    'matches.deleteConfirm': 'Are you sure you want to delete this match?',
    'matches.deleted': 'Match deleted',

    // Analysis
    'analysis.phaseBreakdown': 'Phase breakdown',
    'analysis.phaseBreakdownDesc': 'Share of hot/normal/slump/recovery',
    'analysis.eventBreakdown': 'Event breakdown',
    'analysis.eventBreakdownDesc': 'Frequency of kills, plants, abilities, and more',
    'analysis.ttdDistribution': 'TTD distribution',
    'analysis.ttdDistributionDesc': 'Decision time histogram (ms)',
    'analysis.voiceQuality': 'Voice quality radar',
    'analysis.voiceQualityDesc': 'Clarity, info density, and interruption rate',
    'analysis.comboPerformance': 'Combo win rate',
    'analysis.comboPerformanceDesc': 'Performance of duo/trio combinations',
    'analysis.noData': 'No data',
    'analysis.loading': 'Loading...',
    'analysis.live': 'Live analysis',

    // Match Detail
    'matchDetail.title': 'Match Detail #{id}',
    'matchDetail.liveData': 'Live data',
    'matchDetail.overview': 'Match overview',
    'matchDetail.overviewDesc': 'Map, time, score, and file info',
    'matchDetail.teams': 'Teams',
    'matchDetail.score': 'Score',
    'matchDetail.duration': 'Duration',
    'matchDetail.schedule': 'Start time',
    'matchDetail.endTime': 'End time',
    'matchDetail.summary': 'Key snapshot',
    'matchDetail.summaryDesc': 'TTD, comms quality, and combo winrate',
    'matchDetail.ttdLabel': 'TTD P50 / P90',
    'matchDetail.voiceQuality': 'Voice clarity',
    'matchDetail.comboLabel': 'Top combo',
    'matchDetail.phases': 'Phases',
    'matchDetail.phasesDesc': 'Hot/normal/slump/recovery segments',
    'matchDetail.noPhases': 'No phase data yet',
    'matchDetail.phaseDuration': 'Duration',
    'matchDetail.changePoint': 'Change point',
    'matchDetail.events': 'Events',
    'matchDetail.eventsDesc': 'Kills, plants, and other actions',
    'matchDetail.noEvents': 'No events recorded',
    'matchDetail.ttd': 'Time to decision',
    'matchDetail.ttdDesc': 'P50/P90, mean, and sample breakdown',
    'matchDetail.noTtd': 'No TTD samples',
    'matchDetail.mean': 'Mean',
    'matchDetail.samples': 'Samples',
    'matchDetail.noData': 'No data',
    'matchDetail.voice': 'Voice turns',
    'matchDetail.voiceDesc': 'Clarity, info density, interruption rate',
    'matchDetail.noVoice': 'No voice records',
    'matchDetail.clarity': 'Clarity',
    'matchDetail.infoDensity': 'Info density',
    'matchDetail.interruptions': 'Interruptions',
    'matchDetail.turns': 'Turns',
    'matchDetail.noTranscript': 'No transcript provided',
    'matchDetail.sentiment': 'Sentiment',
    'matchDetail.combos': 'Team combos',
    'matchDetail.combosDesc': 'Attempts, successes, and win rate',
    'matchDetail.noCombos': 'No combo data',
    'matchDetail.comboContext': 'Combo context',
    'matchDetail.attempts': 'Attempts',
    'matchDetail.success': 'Success / Attempts',
    'matchDetail.winRate': 'Win rate',
    
    // Match Upload
    'upload.title': 'Upload Match Demo',
    'upload.description': 'Upload CS official demo file for post-match analysis',
    'upload.selectFile': 'Select Demo File',
    'upload.supportedFormats': 'Supports CS:GO and CS2 .dem format files',
    'upload.clickOrDrag': 'Click or drag file here',
    'upload.maxSize': 'Supports .dem format, max 100MB',
    'upload.reselect': 'Reselect',
    'upload.matchInfo': 'Match Information',
    'upload.fillBasicInfo': 'Fill in basic match information',
    'upload.mapName': 'Map Name',
    'upload.mapPlaceholder': 'e.g.: de_dust2, de_mirage',
    'upload.teamAName': 'Team A Name',
    'upload.teamAPlaceholder': 'Team A',
    'upload.teamBName': 'Team B Name',
    'upload.teamBPlaceholder': 'Team B',
    'upload.teamAScore': 'Team A Score',
    'upload.teamBScore': 'Team B Score',
    'upload.uploading': 'Uploading...',
    'upload.uploadAndAnalyze': 'Upload & Analyze',
    'upload.fileSelected': 'File selected',
    'upload.selectDemFile': 'Please select a .dem format CS demo file',
    'upload.pleaseSelectFile': 'Please select demo file',
    'upload.fillComplete': 'Please fill in complete match information',
    'upload.success': 'Upload successful!',
    'upload.matchSaved': 'Match saved',
    'upload.failed': 'Upload failed',
    'upload.checkFormat': 'Please check file format',
    
    // Topics
    'topics.title': 'Voting & Betting',
    'topics.description': 'Participate in community discussions and predictions',
    'topics.myPoints': 'My Points',
    'topics.createTopic': 'Create Topic',
    'topics.noTopics': 'No active topics',
    'topics.createFirst': 'Create first topic to start interaction',
    'topics.vote': 'Vote',
    'topics.bet': 'Bet',
    'topics.mission': 'Secret Mission',
    'topics.active': 'Active',
    'topics.closed': 'Closed',
    'topics.revealed': 'Revealed',
    'topics.participants': 'Participants',
    'topics.totalPool': 'Total Pool',
    'topics.viewDetail': 'View Details',
    'topics.deleteConfirm': 'Are you sure you want to delete this topic?',
    'topics.deleted': 'Topic deleted',
    'topics.waitForAdmin': 'Waiting for admin to create topics',
    'topics.missionReward': 'Reward +{points} pts',
    'topics.missionOutcome': 'Settled by creator',

    // Topic Detail
    'topic.backToList': 'Back to Topics',
    'topic.status': 'Status',
    'topic.revealTime': 'Reveal Time',
    'topic.yourChoice': 'Your Choice',
    'topic.notParticipated': 'Not Participated',
    'topic.pointsSpent': 'Points Spent',
    'topic.points': 'Points',
    'topic.statistics': 'Statistics',
    'topic.totalVotes': 'Total Votes',
    'topic.options': 'Options',
    'topic.chooseOption': 'Choose an option',
    'topic.betAmount': 'Bet Amount',
    'topic.minBet': 'Minimum 10 points',
    'topic.insufficientPoints': 'Insufficient points',
    'topic.submitVote': 'Submit Vote',
    'topic.submitBet': 'Submit Bet',
    'topic.alreadyParticipated': 'You have already participated',
    'topic.topicClosed': 'Topic closed',
    'topic.selectOption': 'Please select an option',
    'topic.enterBetAmount': 'Please enter bet amount',
    'topic.minBetRequired': 'Minimum bet is 10 points',
    'topic.notEnoughPoints': 'Not enough points',
    'topic.voteSuccess': 'Vote successful!',
    'topic.betSuccess': 'Bet successful!',
    'topic.pointsDeducted': 'Points deducted',
    'chat.revealLoginRequired': 'Please log in to reveal results',
    'chat.noActiveTopics': 'No active topics to settle',
    'chat.revealMessage': 'Winner revealed for "{title}": {choice}. Points settled.',
    'chat.revealSuccess': 'Winner revealed and points settled',
    'chat.revealFailed': 'Reveal failed',
    'chat.autoCreateTopic': 'Auto Create Topic',
    'chat.autoCreateSuccess': 'Topic created automatically',
    'chat.autoCreateFailed': 'Failed to auto-create topic',
    
    // Reveal Dialog
    'reveal.letsSeWhoWins': "LET'S SEE WHO WINS!",
    'reveal.tapToReveal': 'Tap the card to reveal',
    'reveal.winner': 'Winner',
    'reveal.yourPick': 'Your pick',
    'reveal.participated': 'Participated',
    'reveal.notParticipated': "You didn't participate",
    'reveal.pointsAtStake': 'Points at stake',
    'reveal.youWin': 'YOU WIN!',
    'reveal.youLose': 'YOU LOSE',
    'reveal.tapToContinue': 'Tap anywhere to continue',
    'common.close': 'Close',
    
    // Create Topic
    'createTopic.title': 'Create Topic',
    'createTopic.description': 'Create new voting or betting topic',
    'createTopic.basicInfo': 'Basic Information',
    'createTopic.topicTitle': 'Topic Title',
    'createTopic.titlePlaceholder': 'Enter an attractive topic title',
    'createTopic.topicDescription': 'Topic Description',
    'createTopic.descriptionPlaceholder': 'Describe topic content and rules in detail',
    'createTopic.topicType': 'Topic Type',
    'createTopic.typeVote': 'Vote - Anonymous participation, no points cost',
    'createTopic.typeBet': 'Bet - Requires points, win rewards for correct guess',
    'createTopic.optionsSetup': 'Options Setup',
    'createTopic.addOption': 'Add Option',
    'createTopic.optionPlaceholder': 'Option',
    'createTopic.minTwoOptions': 'At least 2 options required',
    'createTopic.revealTime': 'Reveal Time',
    'createTopic.selectDateTime': 'Select topic deadline and reveal time',
    'createTopic.create': 'Create Topic',
    'createTopic.fillRequired': 'Please fill in all required fields',
    'createTopic.success': 'Topic created successfully!',
    'createTopic.adminOnly': 'Only admins can create topics',
    'createTopic.noPermission': 'Insufficient permissions',
    
    // Profile
    'profile.title': 'Profile',
    'profile.info': 'Personal Information',
    'profile.pointsHistory': 'Points History',
    'profile.username': 'Username',
    'profile.role': 'Role',
    'profile.roleAdmin': 'Admin',
    'profile.roleUser': 'User',
    'profile.joinDate': 'Join Date',
    'profile.currentPoints': 'Current Points',
    'profile.pointsSummary': 'Points Summary',
    'profile.totalEarned': 'Total Earned',
    'profile.totalSpent': 'Total Spent',
    'profile.balance': 'Balance',
    'profile.noTransactions': 'No transaction records',
    'profile.transactionType': 'Type',
    'profile.system': 'System Gift',
    'profile.bet': 'Bet Cost',
    'profile.win': 'Win Reward',
    'profile.refund': 'Refund',
    'profile.relatedTopic': 'Related Topic',
    
    // Discord
    'discord.title': 'Discord Bot Settings',
    'discord.description': 'Configure and manage your Discord bot',
    'discord.tokenSetup': 'Bot Token Setup',
    'discord.enterToken': 'Enter your Discord Bot Token',
    'discord.tokenPlaceholder': 'Paste your Bot Token',
    'discord.howToGet': 'How to get Token?',
    'discord.howToCreate': 'How to create a Discord Bot',
    'discord.step1': 'Visit Discord Developer Portal',
    'discord.step2': 'Create a new app or select existing',
    'discord.step3': 'Enable "Message Content Intent" in bot settings',
    'discord.step4': 'Copy the Bot Token and paste it above',
    'discord.step5': 'Invite the bot to your server via OAuth2 URL',
    'discord.saveToken': 'Save Token',
    'discord.botStatus': 'Bot Status',
    'discord.statusDescription': 'Check the current Discord bot status',
    'discord.runningStatus': 'Status',
    'discord.botUsername': 'Bot Username',
    'discord.serverCount': 'Server Count',
    'discord.servers': 'servers',
    'discord.tokenHelp': 'Get the Bot Token from the Discord Developer Portal',
    'discord.botConfig': 'Bot Configuration',
    'discord.configDescription': 'Configure Discord Bot Token and permissions',
    'discord.online': 'Online',
    'discord.offline': 'Offline',
    'discord.startBot': 'Start Bot',
    'discord.stopBot': 'Stop Bot',
    'discord.features': 'Features',
    'discord.aiChat': 'AI Coach Q&A (!ask)',
    'discord.voiceJoin': 'Voice Channel (!join/!leave)',
    'discord.dataQuery': 'Data Query (!stats, !matches)',
    'discord.adminOnly': 'Admin Only',
    'discord.tokenSaved': 'Token saved',
    'discord.botStarted': 'Bot started',
    'discord.botStopped': 'Bot stopped',
    'discord.enterTokenFirst': 'Please enter Bot Token first',
    'discord.requiredPermissions': 'Required Permissions',
    'discord.permissionRead': 'Read messages',
    'discord.permissionSend': 'Send messages',
    'discord.permissionConnect': 'Connect to voice channels',
    'discord.permissionSpeak': 'Speak in voice channels',
    'discord.availableCommands': 'Available Commands',
    'discord.commandsDescription': 'Use these commands to interact with the bot in Discord',
    'discord.dataSectionTitle': '📊 Data Queries',
    'discord.voiceSectionTitle': '🎯 Voice Features',
    'discord.interactSectionTitle': '🎲 Interactive Features',
    'discord.aiSectionTitle': '🤖 AI Assistant',
    'discord.statsCommand': 'View match statistics',
    'discord.matchesCommand': 'View match list',
    'discord.joinCommand': 'Join voice channel',
    'discord.leaveCommand': 'Leave voice channel',
    'discord.topicsCommand': 'View voting topics',
    'discord.voteCommand': 'Join voting',
    'discord.askCommand': 'Ask the AI coach',
    'discord.helpCommand': 'View help',
    'discord.startFailed': 'Start failed',
    'discord.stopFailed': 'Stop failed',
    
    // App Title
    'app.title': 'FPS Team Post-Match Coach AI Agent',
    'app.subtitle': 'Data-Driven FPS Team Post-Match Analysis Platform',
    'app.tagline': 'Transform post-match review from "feeling-driven" to "data-driven + interactive"',
    'app.enterSystem': 'Enter System',
    'app.startJourney': 'Click to start your data analysis journey',

    // Pages
    'pages.analysis': 'Analysis',
    'pages.settings': 'Settings',
    'pages.matchDetail': 'Match Detail',
    'pages.componentShowcase': 'Component Showcase',
    'pages.notFound': 'Not Found',

    // Component Showcase
    'showcase.title': 'Shadcn/ui Component Library',
    'showcase.textColors': 'Text Colors',
    'showcase.foreground': 'Foreground (Default)',
    'showcase.defaultText': 'Default text color for main content',
    'showcase.mutedForeground': 'Muted Foreground',
    'showcase.mutedText': 'Muted text for secondary information',
    'showcase.primary': 'Primary',
    'showcase.primaryText': 'Primary brand color text',
    'showcase.secondaryForeground': 'Secondary Foreground',
    'showcase.secondaryText': 'Secondary action text color',
    'showcase.accentForeground': 'Accent Foreground',
    'showcase.accentText': 'Accent text for emphasis',
    'showcase.destructive': 'Destructive',
    'showcase.destructiveText': 'Error or destructive action text',
    'showcase.cardForeground': 'Card Foreground',
    'showcase.cardText': 'Text color on card backgrounds',
    'showcase.popoverForeground': 'Popover Foreground',
    'showcase.popoverText': 'Text color in popovers',
    'showcase.colorCombinations': 'Color Combinations',
    'showcase.primaryBg': 'Primary background with foreground text',
    'showcase.secondaryBg': 'Secondary background with foreground text',
    'showcase.mutedBg': 'Muted background with foreground text',
    'showcase.accentBg': 'Accent background with foreground text',
    'showcase.destructiveBg': 'Destructive background with foreground text',
    'showcase.cardBg': 'Card background with foreground text',
    'showcase.popoverBg': 'Popover background with foreground text',
    'showcase.backgroundBg': 'Default background with foreground text',

    // Not Found
    'notFound.title': 'Page Not Found',
    'notFound.description': 'The page you are looking for does not exist',
    'notFound.backHome': 'Back to Home',

    // Teams
    'teams.title': 'Teams',
    'teams.description': 'Manage your teams and members',
    'teams.myTeams': 'My Teams',
    'teams.discoverTeams': 'Discover Teams',
    'teams.createTeam': 'Create Team',
    'teams.joinTeam': 'Join Team',
    'teams.noTeams': 'No teams yet',
    'teams.noTeamsDesc': 'Create a new team or join an existing one with an invite code',
    'teams.noPublicTeams': 'No public teams',
    'teams.noPublicTeamsDesc': 'No public teams available to join',
    'teams.maxMembers': 'Max {count} members',
    'teams.public': 'Public',
    'teams.noDescription': 'No team description',
    'teams.roleOwner': 'Owner',
    'teams.roleAdmin': 'Admin',
    'teams.roleMember': 'Member',
    'teams.createSuccess': 'Team created successfully!',
    'teams.joinSuccess': 'Successfully joined team {name}!',
    'teams.createNew': 'Create New Team',
    'teams.createDesc': 'Create a team to organize your teammates',
    'teams.teamName': 'Team Name',
    'teams.teamNamePlaceholder': 'e.g.: Phoenix Rising',
    'teams.teamTag': 'Team Tag',
    'teams.teamTagPlaceholder': 'e.g.: PHX',
    'teams.teamTagHint': '2-6 character short identifier',
    'teams.teamDescription': 'Team Description',
    'teams.teamDescPlaceholder': 'Describe your team...',
    'teams.maxMembersLabel': 'Max Members',
    'teams.publicTeam': 'Public Team',
    'teams.publicTeamHint': 'Allow other players to discover and apply to join',
    'teams.creating': 'Creating...',
    'teams.joinByCode': 'Join Team',
    'teams.joinByCodeDesc': 'Enter invite code to join an existing team',
    'teams.inviteCode': 'Invite Code',
    'teams.inviteCodePlaceholder': 'e.g.: A1B2C3D4',
    'teams.inviteCodeHint': 'Get invite code from team members',
    'teams.joining': 'Joining...',
    
    // Team Detail
    'teamDetail.notFound': 'Team not found',
    'teamDetail.notFoundDesc': 'This team may have been disbanded or you do not have access',
    'teamDetail.backToList': 'Back to Teams',
    'teamDetail.members': 'Members',
    'teamDetail.youAre': 'You are {role}',
    'teamDetail.editTeam': 'Edit Team',
    'teamDetail.leaveTeam': 'Leave Team',
    'teamDetail.disbandTeam': 'Disband Team',
    'teamDetail.confirmLeave': 'Leave team?',
    'teamDetail.leaveHint': 'You will need to get a new invite code to rejoin.',
    'teamDetail.confirmDisband': 'Disband team?',
    'teamDetail.disbandHint': 'This action cannot be undone. All members will be removed and team data will be permanently deleted.',
    'teamDetail.confirmLeaveBtn': 'Confirm Leave',
    'teamDetail.confirmDisbandBtn': 'Confirm Disband',
    'teamDetail.leftTeam': 'Left team',
    'teamDetail.disbanded': 'Team disbanded',
    'teamDetail.inviteCodeLabel': 'Invite Code · Share with friends to join',
    'teamDetail.codeRefreshed': 'Invite code refreshed',
    'teamDetail.emptySlot': 'Empty Slot',
    
    // Team Member
    'teamMember.edit': 'Edit',
    'teamMember.kick': 'Remove Member',
    'teamMember.transfer': 'Transfer Ownership',
    'teamMember.editMember': 'Edit Member',
    'teamMember.editMemberDesc': 'Modify {name}\'s information',
    'teamMember.nickname': 'Nickname',
    'teamMember.nicknamePlaceholder': 'Team nickname',
    'teamMember.position': 'Position',
    'teamMember.positionPlaceholder': 'Select position',
    'teamMember.role': 'Role',
    'teamMember.updated': 'Member info updated',
    'teamMember.confirmKick': 'Remove member?',
    'teamMember.kickHint': 'Are you sure you want to remove {name} from the team?',
    'teamMember.confirmKickBtn': 'Confirm Remove',
    'teamMember.kicked': 'Member removed',
    'teamMember.confirmTransfer': 'Transfer ownership?',
    'teamMember.transferHint': 'Are you sure you want to transfer ownership to {name}? You will become an admin.',
    'teamMember.confirmTransferBtn': 'Confirm Transfer',
    'teamMember.transferred': 'Ownership transferred',
    'teamMember.saving': 'Saving...',
    
    // Team Edit
    'teamEdit.title': 'Edit Team',
    'teamEdit.description': 'Modify team info and settings',
    'teamEdit.updated': 'Team info updated',
    
    // Team Status
    'teamStatus.online': 'Online',
    'teamStatus.offline': 'Offline',
    'teamStatus.inGame': 'In Game',
    'teamStatus.away': 'Away',
    'teamStatus.onlineCount': '{online}/{total} online',
    'teamStatus.refresh': 'Refresh',
    'teamStatus.teamSettings': 'Team Settings',
    'teamStatus.inviteCode': 'Invite Code',
    'teamStatus.members': 'Members',
    'teamStatus.memberCount': '{count}/{max}',
    'teamStatus.emptySlots': 'Empty Slots',
    'teamStatus.waitingToJoin': 'Waiting to join...',
    'teamStatus.viewDetails': 'View Team Details',
    'teamStatus.noTeam': 'No teams yet',
    'teamStatus.noTeamDesc': 'Create a new team or join an existing one with an invite code',
    'teamStatus.team': 'Team',
    'teamStatus.joinOrCreate': 'Join or create a team to collaborate',
    'teamStatus.loadFailed': 'Unable to load team info',
    
    // Positions
    'position.IGL': 'IGL',
    'position.Entry': 'Entry',
    'position.AWPer': 'AWPer',
    'position.Support': 'Support',
    'position.Lurker': 'Lurker',
    'position.Rifler': 'Rifler',
    'position.Flex': 'Flex',
    
    // Team Themes
    'teamTheme.title': 'Theme',
    'teamTheme.selectTheme': 'Select Theme',
    'teamTheme.deepBlue': 'Deep Blue',
    'teamTheme.deepBlueDesc': 'Classic esports theme',
    'teamTheme.crimson': 'Crimson Fire',
    'teamTheme.crimsonDesc': 'Battle & Passion',
    'teamTheme.gold': 'Glory Gold',
    'teamTheme.goldDesc': 'Elite & Management',
    'teamTheme.purple': 'Electric Purple',
    'teamTheme.purpleDesc': 'Community & Trend',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'en' || saved === 'zh') ? saved : 'zh';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['zh']] || key;
  };

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
